In [7]:
import numpy as np

In [7]:
# Linear Algebra Exercise 1

A = np.array([[7, -2, 1],
              [-1, 3, 0],
              [8, -2, 4]])

B = np.array([[10],
              [5],
              [3]])

A = np.asmatrix(A)
B = np.asmatrix(B)

x = A.I*B

x

matrix([[ 2.61111111],
        [ 2.53703704],
        [-3.2037037 ]])

In [11]:
# Linear Algebra Exercise 2 & 3

x = np.array([[1],
              [1]])

y = np.array([[2],
              [3]])

x = np.asmatrix(x)
y = np.asmatrix(y)

inner_product = x.T @ y

inner_product

matrix([[5]])

In [16]:
# Linear Algebra Exercise 4

A = np.array([[4, 1],
              [3, 2],
              [1, 3]])

B = np.array([[2],
              [1],
              [0]])

A = np.asmatrix(A)
B = np.asmatrix(B)

X_star = (A.T * A).I * A.T * B

X_star

matrix([[ 0.52307692],
        [-0.2       ]])