In [1]:
import numpy as np
import cvxpy as cvx

In [3]:
### Exercise 1

f = np.array([[2],
              [3]])

A = np.array([[2, 2],
              [1, 2]])

B = np.array([[20],
              [14]])

lb = np.array([[1],
               [2]])

x = cvx.Variable([2, 1])

obj = cvx.Maximize(f.T @ x)
constraints = [A@x <= B, lb <= x]

prob = cvx.Problem(obj, constraints)
result = prob.solve()

print(x.value)
print(result)

[[6.]
 [4.]]
23.999999999256048


In [5]:
### Exercise 2

f = np.array([[1], [1]])
H = np.array([[1/2, 0],
              [0, 0]])

A = np.array([[2, 3],
              [3, 4],
              [2, 4]])
B = np.array([[12],
              [80],
              [80]])

lb = np.array([[0],
               [0]])

x = cvx.Variable([2, 1])

obj = cvx.Minimize(cvx.quad_form(x, H) + f.T@x)
constraints = [A@x <= B, lb <= x]

prob = cvx.Problem(obj, constraints)
result = prob.solve()

print(x.value)
print(result)

[[2.45778468e-25]
 [3.82056353e-31]]
2.457788498668255e-25


In [18]:
### Exercise 3

H = np.matrix([[5, -1],
               [-1, 5]])
g = np.matrix([[-4],
               [4]])

x = np.zeros((2, 1))
alpha = 0.05

for repet in range(25):
    df = 2*H*x + g
    x = x - alpha*df

print(x)

[[ 0.33333333]
 [-0.33333333]]
