In [1]:
import numpy as np
import pandas as pd
from sklearn import svm
from sklearn import metrics

### 실습 과제 1. 데이터 불러온 후 NaN 값이 있다면 해당 행 제거하고, train_data : test_data = 7:3 split
#### 종속변수는 PKT_Y, 나머지 변수들이 독립변수

In [5]:
df = pd.read_csv("./data/contest.csv")

df.head()

No.   LOT_ID  WF_ID  X_AXIS  Y_AXIS GRADE_CD  G_A  G_B  G_C  G_D  ...  \
0  48159  ABC1236     13      59      32       SQ    0    0    0    0  ...   
1  60178  ABC1258      2      45      14       SQ    0    0    0    0  ...   
2  60860  ABC1258     15      50      14       SQ    0    0    0    0  ...   
3  25012  ABC1236      1      45      13       SQ    0    0    0    0  ...   
4  86262  ABC1236      3      51      13       SQ    0    0    0    0  ...   

   Weight_Bound_L  Weight_Bound_M  Weight_Bound_N  Weight_Bound_O  \
0             0.0             0.0             0.0             0.0   
1             0.0             0.0             0.0             0.0   
2             0.0             0.0             0.0             0.0   
3             0.0             0.0             0.0             0.0   
4             0.0             0.0             0.0             0.0   

   Weight_Bound_P  Weight_Bound_Q  Weight_Bound_R  Weight_Bound_S  \
0             0.0             0.0        0.000000        0.000000   
1             0.0             0.0        0.000000        0.000000   
2             0.0             0.0        3.452381       81.583333   
3             0.0             0.0        0.000000        0.000000   
4             0.0             0.0        0.000000        0.000000   

   Weight_Bound_T  PKT_Y  
0             0.0    1.0  
1             0.0    1.0  
2             0.0    1.0  
3             0.0    1.0  
4             0.0    1.0  

[5 rows x 87 columns]

In [6]:
df.describe(include="all")

No.   LOT_ID        WF_ID       X_AXIS       Y_AXIS  \
count     2500.000000     2500  2500.000000  2500.000000  2500.000000   
unique            NaN        3          NaN          NaN          NaN   
top               NaN  ABC1258          NaN          NaN          NaN   
freq              NaN     1231          NaN          NaN          NaN   
mean     58457.710800      NaN    12.842000    38.779200    27.032400   
std      35589.053486      NaN     7.460409    14.360339     8.964212   
min        105.000000      NaN     1.000000    11.000000    11.000000   
25%      27833.750000      NaN     6.000000    27.000000    20.000000   
50%      57130.000000      NaN    13.000000    38.000000    27.000000   
75%      85205.750000      NaN    19.000000    51.000000    34.000000   
max     128225.000000      NaN    25.000000    68.000000    44.000000   

       GRADE_CD          G_A         G_B          G_C          G_D  ...  \
count      2500  2500.000000  2500.00000  2500.000000  2500.000000  ...   
unique        4          NaN         NaN          NaN          NaN  ...   
top          SQ          NaN         NaN          NaN          NaN  ...   
freq       1751          NaN         NaN          NaN          NaN  ...   
mean        NaN     1.639200     1.61560     1.766000     1.844800  ...   
std         NaN     6.968246     6.90615     7.029183     6.442524  ...   
min         NaN     0.000000     0.00000     0.000000     0.000000  ...   
25%         NaN     0.000000     0.00000     0.000000     0.000000  ...   
50%         NaN     0.000000     0.00000     0.000000     0.000000  ...   
75%         NaN     0.000000     0.00000     0.000000     0.000000  ...   
max         NaN    84.000000    84.00000    84.000000    60.000000  ...   

        Weight_Bound_L  Weight_Bound_M  Weight_Bound_N  Weight_Bound_O  \
count      2500.000000     2500.000000     2500.000000     2500.000000   
unique             NaN             NaN             NaN             NaN   
top                NaN             NaN             NaN             NaN   
freq               NaN             NaN             NaN             NaN   
mean          1.100230        0.884604        0.974666        1.695392   
std          10.618900        8.894689       10.097390       18.942232   
min           0.000000        0.000000        0.000000        0.000000   
25%           0.000000        0.000000        0.000000        0.000000   
50%           0.000000        0.000000        0.000000        0.000000   
75%           0.000000        0.000000        0.000000        0.000000   
max         244.642857      239.819444      247.500000      683.416667   

        Weight_Bound_P  Weight_Bound_Q  Weight_Bound_R  Weight_Bound_S  \
count      2500.000000     2500.000000     2500.000000     2500.000000   
unique             NaN             NaN             NaN             NaN   
top                NaN             NaN             NaN             NaN   
freq               NaN             NaN             NaN             NaN   
mean          2.443549        2.272934        7.761293        8.533709   
std          22.176382       22.150841       38.262314       38.278556   
min           0.000000        0.000000        0.000000        0.000000   
25%           0.000000        0.000000        0.000000        0.000000   
50%           0.000000        0.000000        0.000000        0.000000   
75%           0.000000        0.000000        0.000000        0.000000   
max         618.750000      617.291667      600.000000      611.619048   

        Weight_Bound_T        PKT_Y  
count      2500.000000  1970.000000  
unique             NaN          NaN  
top                NaN          NaN  
freq               NaN          NaN  
mean          1.167709     0.507614  
std          10.442140     0.500069  
min           0.000000     0.000000  
25%           0.000000     0.000000  
50%           0.000000     1.000000  
75%           0.000000     1.000000  
max         341.714286     1.000000  

[11 r

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 87 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   No.             2500 non-null   int64  
 1   LOT_ID          2500 non-null   object 
 2   WF_ID           2500 non-null   int64  
 3   X_AXIS          2500 non-null   int64  
 4   Y_AXIS          2500 non-null   int64  
 5   GRADE_CD        2500 non-null   object 
 6   G_A             2500 non-null   int64  
 7   G_B             2500 non-null   int64  
 8   G_C             2500 non-null   int64  
 9   G_D             2500 non-null   int64  
 10  G_E             2500 non-null   int64  
 11  G_F             2500 non-null   int64  
 12  G_G             2500 non-null   int64  
 13  G_H             2500 non-null   float64
 14  G_I             2500 non-null   int64  
 15  G_J             2500 non-null   int64  
 16  G_K             2500 non-null   int64  
 17  G_L             2500 non-null   i

In [14]:
# PKT_Y에 NULL값 많음. 제거

df = df.dropna(subset=["PKT_Y"], how="any")
df.shape

(1970, 87)

In [27]:
from sklearn.model_selection import train_test_split

# 0   No.             2500 non-null   int64 
# 1   LOT_ID          2500 non-null   object 
# 2   WF_ID           2500 non-null   int64  
# 3   X_AXIS          2500 non-null   int64  
# 4   Y_AXIS          2500 non-null   int64  
# 5   GRADE_CD        2500 non-null   object 

X = df.drop(labels=["No.", "LOT_ID", "WF_ID", "X_AXIS", "Y_AXIS", "GRADE_CD", "PKT_Y"], axis=1)
Y = df["PKT_Y"]

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=10)

print(X_train.shape, X_test.shape, Y_train.shape, Y_test.shape)

(1379, 80) (591, 80) (1379,) (591,)


### 실습 과제 2. 선형 커널, 3차항 커널, RBF 커널, 시그모이드 커널로 각각 SVM 모델 구현 후 accuracy, F1 score, confusion matrix, precision, recall (C=1, gamma = 0.1)

In [28]:
from sklearn import svm

svm_linear = svm.SVC(kernel="linear", C=1, gamma=0.1)
svm_linear.fit(X_train, Y_train)

SVC(C=1, gamma=0.1, kernel='linear')

In [41]:
svm_poly3d = svm.SVC(kernel="poly", degree=3, C=1, gamma=0.1)
svm_poly3d.fit(X_train, Y_train)

SVC(C=1, gamma=0.1, kernel='poly')

In [30]:
svm_rbf = svm.SVC(kernel="rbf", C=1, gamma=0.1)
svm_rbf.fit(X_train, Y_train)

SVC(C=1, gamma=0.1)

In [31]:
svm_sigmoid = svm.SVC(kernel='sigmoid', C=1, gamma=0.1)
svm_sigmoid.fit(X_train, Y_train)

SVC(C=1, gamma=0.1, kernel='sigmoid')

In [ ]:
from sklearn.metrics import confusion_matrix, precision_score, accuracy_score, f1_score, recall_score

In [42]:
# linear kernel metrics

linear_predict = svm_linear.predict(X_test)

print("linear accuracy score :", accuracy_score(Y_test, linear_predict))
print("linear F1 score :", f1_score(Y_test, linear_predict))
print("linear precision score :", precision_score(Y_test, linear_predict))
print("linear recall score :", recall_score(Y_test, linear_predict))
print("linear confusion_matrix :\n", confusion_matrix(Y_test, linear_predict))

linear accuracy score : 0.583756345177665
linear F1 score : 0.5020242914979757
linear precision score : 0.656084656084656
linear recall score : 0.4065573770491803
linear confusion_matrix :
 [[221  65]
 [181 124]]


In [43]:
# poly3d kernel metrics

poly3d_predict = svm_poly3d.predict(X_test)

print("poly3d accuracy :", accuracy_score(Y_test, poly3d_predict))
print("poly3d F1 score :", f1_score(Y_test, poly3d_predict))
print("poly3d precision score :", precision_score(Y_test, poly3d_predict))
print("poly3d recall score :", recall_score(Y_test, poly3d_predict))
print("poly3d confusion_matrix :\n", confusion_matrix(Y_test, poly3d_predict))

poly3d accuracy : 0.5820642978003384
poly3d F1 score : 0.5240847784200385
poly3d precision score : 0.6355140186915887
poly3d recall score : 0.4459016393442623
poly3d confusion_matrix :
 [[208  78]
 [169 136]]


In [44]:
# rbf kernel metrics

rbf_predict = svm_rbf.predict(X_test)

print("rbf accuracy :", accuracy_score(Y_test, rbf_predict))
print("rbf F1 score :", f1_score(Y_test, rbf_predict))
print("rbf precision score :", precision_score(Y_test, rbf_predict))
print("rbf recall score :", recall_score(Y_test, rbf_predict))
print("rbf confusion_matrix :\n", confusion_matrix(Y_test, rbf_predict))

rbf accuracy : 0.5769881556683587
rbf F1 score : 0.6458923512747875
rbf precision score : 0.5685785536159601
rbf recall score : 0.7475409836065574
rbf confusion_matrix :
 [[113 173]
 [ 77 228]]


In [45]:
# sigmoid kernel metrics

sigmoid_predict = svm_sigmoid.predict(X_test)

print("sigmoid accuracy :", accuracy_score(Y_test, sigmoid_predict))
print("sigmoid F1 score :", f1_score(Y_test, sigmoid_predict))
print("sigmoid precision score :", precision_score(Y_test, sigmoid_predict))
print("sigmoid recall score :", recall_score(Y_test, sigmoid_predict))
print("sigmoid confusion_matrix :\n", confusion_matrix(Y_test, sigmoid_predict))

sigmoid accuracy : 0.36717428087986465
sigmoid F1 score : 0.3848684210526316
sigmoid precision score : 0.38613861386138615
sigmoid recall score : 0.3836065573770492
sigmoid confusion_matrix :
 [[100 186]
 [188 117]]


### 실습 과제 3. 하이퍼 파라미터 C 값(0.01, 0.1, 1, 10)에 따른 RBF 커널을 SVM 모델의 accuracy와 F1 score 변화 관찰

In [49]:
hyperparameter_C_list = [0.01, 0.1, 1, 10]

for C_value in hyperparameter_C_list:
    svm_rbf_c = svm.SVC(kernel="rbf", C=C_value, gamma=0.1)
    svm_rbf_c.fit(X_train, Y_train)
    
    rbf_c_predict = svm_rbf_c.predict(X_test)
    
    print("-" * 30)
    print("C value : {}".format(C_value))
    print("accuracy :", accuracy_score(Y_test, rbf_c_predict))
    print("F1 score :", f1_score(Y_test, rbf_c_predict))
    print("-" * 30)

------------------------------
C value : 0.01
accuracy : 0.5160744500846024
F1 score : 0.6808035714285715
------------------------------
------------------------------
C value : 0.1
accuracy : 0.5465313028764806
F1 score : 0.6555269922879178
------------------------------
------------------------------
C value : 1
accuracy : 0.5769881556683587
F1 score : 0.6458923512747875
------------------------------
------------------------------
C value : 10
accuracy : 0.5702199661590525
F1 score : 0.6520547945205479
------------------------------


### 실습 과제 4. 하이퍼 파라미터 gamma 값(0.005,0.01,0.1, 1)에 따른 RBF 커널을 SVM 모델의 accuracy와 F1 score 변화 관찰

In [50]:
hyperparameter_gamma_list = [0.005, 0.01, 0.1, 1]

for gamma_value in hyperparameter_gamma_list:
    svm_rbf_gamma = svm.SVC(kernel="rbf", C=1, gamma=gamma_value)
    svm_rbf_gamma.fit(X_train, Y_train)
    
    rbf_gamma_predict = svm_rbf_gamma.predict(X_test)
    
    print("-" * 30)
    print("gamma value : {}".format(gamma_value))
    print("accuracy :", accuracy_score(Y_test, rbf_gamma_predict))
    print("F1 score :", f1_score(Y_test, rbf_gamma_predict))
    print("-" * 30)

------------------------------
gamma value : 0.005
accuracy : 0.6040609137055838
F1 score : 0.5894736842105263
------------------------------
------------------------------
gamma value : 0.01
accuracy : 0.6006768189509306
F1 score : 0.6143790849673203
------------------------------
------------------------------
gamma value : 0.1
accuracy : 0.5769881556683587
F1 score : 0.6458923512747875
------------------------------
------------------------------
gamma value : 1
accuracy : 0.544839255499154
F1 score : 0.6699386503067485
------------------------------


### 실습 과제 5. 하이퍼 파라미터 degree(1,2,3,4,5)에 따른 다항식 커널 SVM 모델 accuracy와 F1 score 변화 관찰

In [52]:
hyperparameter_degree_list = [1, 2, 3, 4, 5]

for degree_value in hyperparameter_degree_list:
    svm_polynd = svm.SVC(kernel="poly", degree=degree_value, C=1, gamma=0.1)
    svm_polynd.fit(X_train, Y_train)
    
    polynd_predict = svm_polynd.predict(X_test)
    
    print("-" * 30)
    print("degree value : {}".format(degree_value))
    print("accuracy :", accuracy_score(Y_test, polynd_predict))
    print("F1 score :", f1_score(Y_test, polynd_predict))
    print("-" * 30)

------------------------------
degree value : 1
accuracy : 0.5803722504230119
F1 score : 0.4979757085020242
------------------------------
------------------------------
degree value : 2
accuracy : 0.5668358714043993
F1 score : 0.5133079847908745
------------------------------
------------------------------
degree value : 3
accuracy : 0.5820642978003384
F1 score : 0.5240847784200385
------------------------------
------------------------------
degree value : 4
accuracy : 0.5820642978003384
F1 score : 0.5330812854442345
------------------------------
------------------------------
degree value : 5
accuracy : 0.583756345177665
F1 score : 0.5477941176470589
------------------------------
